### ISSUE TITLE
Presenting good app the wrong way.

### ISSUE THREAD

**Issue by infowarz** [Grinsafe/website#1]
Hello,

This app sounds like a better Idea for encrypting users passwords, and notes that has come along YET!
Screen Shot Attached and MORE if needed to prove point.

NOTICE: the web Font on your web page is a 4 to 4.5 FONT! 

Your web page has to be ZOOMED to 300% (THREE HUNDRED) in CHROME to be somewhat able to READ words. Same in Firefox, Sea Monkey, Opera, Maxthon and Safari. Font size tested in Word, Open Office, Kingsoft Office, Abiword, and both Kompzer, and TinyMCE. (that is a total of 6 apps that show the 4.5 or LESS FONT!  We who have 12 inch screes or below are FORCED to ZOOM to be somewhat able to SEE to READ the 4.5 FONT.

The Font in this box is a 12 FONT, easy to read HUH?

As you should know.... presenting an app or addon is PRIME Need in order to distribute said app!

FACT: No one should have to ZOOM ANY browser in order to READ the text on the page, image, screen shot or otherwise. 
Web builders should KNOW how to OPTIMIZE a web site, before they "publish" any site on the web.

![grinsafe com](https://cloud.githubusercontent.com/assets/5262481/9838345/40ffea68-5a21-11e5-81e9-21ebbaebbc0d.png)
   
![github com bug page](https://cloud.githubusercontent.com/assets/5262481/9838350/731d51d4-5a21-11e5-8e09-b7a1f6aefc81.png)

**Comment by brainfoolong** [comment]
I have absolutely no clue what do you want. This app is only available for chrome and firefox, don't know why you talk about other browsers. Also the font on grinsafe is definetly a normal font size when you look at the page.css `font-size:14px`, so also i cannot see any problem here.
You only spam and rage around here so i'll close this.

**Comment by infowarz** [comment]
Wow thanks.... that reply was very fast! 

The "problem" has NOTHING to do with your extension. 
Your extension is great!
Both YOUR site, which YOU can have OPTIMIZED so we clients / users can view  easily!

As you may know.... "optimized" is where anyone can view a site at 100% setting on their browser(s) 4 inch, to 12 inch screens....and be able to SEE to read the text """ without """ Zooming! That is one part of "optimized."  Do you understand that statement?

NO this is NOT "flaming" nor spam... just "suggestions" from someone who has been building and viewing web sites for 13 YEARS. 

I do like to help great developers move their work, so I make ""suggestions" to optimize THEIR sites. 

That's is ALL and really sorry I bothered you!

**Comment by infowarz** [comment]
PS... the only "rage" is in you!

**Comment by brainfoolong** [comment]
Sorry for my language, i misunderstood your suggestions, i don't wanted to be rude. 
Grinsafe.com also uses a `font-size: 14px;`, maybe you mean the "screenshot pictures" in it? They are smaller for sure, to fit into the site. Also, as i said before, grinsafe.com will be closed soon, the app remains online on github.
Sorry again for my "rage" comment, i've deleted it after i've written it because i know that was wrong :) Thx for trying to help-
